In [1]:
import numpy as np 

In [2]:
from __future__ import division # import division

In [3]:
5/2

2.5

In [7]:
arr1 = np.array([[1,2,3,4],[8,9,10,11]])

In [8]:
arr1*arr1   #like 1*1,2*2,3*3.....

array([[  1,   4,   9,  16],
       [ 64,  81, 100, 121]])

In [9]:
arr1 - arr1 #like 1-1,2-2,3-3...

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [10]:
1/arr1      #1/1,2/1,3/1

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.125     , 0.11111111, 0.1       , 0.09090909]])

In [11]:
arr1 ** 3 # 1*1*1,2*2*2,3*3*3

array([[   1,    8,   27,   64],
       [ 512,  729, 1000, 1331]], dtype=int32)